### ISSUE TITLE
mpmathify should work for complex sympy numbers

### ISSUE THREAD

**Issue by vks** [mpmath/mpmath#194]
```
>>> from sympy import *
>>> mpmath.mpmathify(S(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sympy/mpmath/mptypes.py", line 363, in convert
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from 1

Let's also make sure that sympy matrices are supported.
```

Original issue for #194: http://code.google.com/p/mpmath/issues/detail?id=154
Original author: https://code.google.com/u/Vinzent.Steinberg@gmail.com/
Original owner: https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by skirpichev** [comment]
I think it's working:
```
In [2]: mpmath.mpmathify(S(1))
Out[2]: mpf('1.0')

In [3]: mpmath.mpmathify(S(1)+I)
Out[3]: mpc(real='1.0', imag='1.0')
```
