### ISSUE TITLE
no floor division and divmod for mpf types

### ISSUE THREAD

**Issue by ces42** [mpmath/mpmath#333]
floor division isn't implemented for `mpf`

```
>>> mpf(1).__floordiv__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'mpf' object has no attribute '__floordiv__'
```

`divmod` doesn't seem to be implemented for `mpf` regardless of the type combination 

```
>>> mpf(1).__divmod__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'mpf' object has no attribute '__divmod__'
```

**Comment by skirpichev** [comment]
Indeed, this should be here as:
```pycon
>>> isinstance(mpf(1), numbers.Real)
True
```
