### ISSUE TITLE
 Eigenvalue decomposition iv arithmetic does not work

### ISSUE THREAD

**Issue by kulalexey** [mpmath/mpmath#355]
'FPContext' object has no attribute 'hypot' error
 and same for interval arithmetic

To reproduce run:
```
from mpmath import fp
fp.eig(fp.matrix([[1,2], [3,4]]))
```
mpmath version: '0.19'

**Comment by fredrik-johansson** [comment]
This should definitely be fixed for fp. However, note that the eigenvalue algorithm will not work as expected with intervals (i.e. even if it is made to run, it will not guarantee computing correct intervals).

**Comment by skirpichev** [comment]
fp part was fixed in #798

**Comment by skirpichev** [comment]
```pycon
>>> iv.eig(fp.matrix([[1,2], [3,4]]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/matrices/eigen.py", line 761, in eig
    hessenberg_qr(ctx, A, Q)
  File "/home/sk/src/mpmath/mpmath/matrices/eigen.py", line 481, in hessenberg_qr
    qr_step(ctx, n0, n1, A, Q, shift)
  File "/home/sk/src/mpmath/mpmath/matrices/eigen.py", line 295, in qr_step
    v = ctx.hypot(ctx.hypot(ctx.re(c), ctx.im(c)), ctx.hypot(ctx.re(s), ctx.im(s)))
        ^^^^^^^^^
AttributeError: 'MPIntervalContext' object has no attribute 'hypot'. Did you mean: 'hyper'?
```
