### ISSUE TITLE
from_str: wrong parsing with underscores after decimal

### ISSUE THREAD

**Issue by cbm755** [mpmath/mpmath#377]
This works:
````
>>> mpmath.libmp.from_str('1_234.567891', 80)
(0, mpz(91095031707585398740483), -66, 77)
>>> mpmath.libmp.to_str(_, 24)
'1234.567891'
````

But underscores placed *after* the decimal point shift the decimal point incorrectly:
````
>>> mpmath.libmp.from_str('1_234.567_891', 80)
(0, mpz(1166016405857093103878183), -73, 80)
>>> mpmath.libmp.to_str(_, 24)
'123.4567891'

>>> mpmath.libmp.from_str('1_234.567_8_9_1', 80)
(0, mpz(746250499748539586482037), -79, 80)
>>> mpmath.libmp.to_str(_, 24)
'1.234567891'
````

The docs say "The literal syntax accepted is the same as for Python floats".  But this is not so:
````
>>> 1_234.567_8_9_1
1234.567891
````

**Comment by symbolique** [comment]
It can even throw an error:
```
>>> mpmath.libmp.from_str('1.0_0', 80)
ValueError: invalid literal for int() with base 10: '10_'
```

Other differences with Python floats:
- `>>> mpmath.libmp.from_str('.000', 80)`
`ValueError: invalid literal for int() with base 10: ''`
- the documentation should mention that unlike float(), it accepts rationals of the form "123/456"

**Comment by skirpichev** [comment]
```python
>>> import mpmath
>>> mpmath.libmp.from_str('1_234.567891', 80)
(0, mpz(91095031707585398740483), -66, 77)
>>> mpmath.libmp.to_str(_, 24)
'1234.567891'
>>> mpmath.libmp.from_str('1_234.567_891', 80)
(0, mpz(91095031707585398740483), -66, 77)
>>> mpmath.libmp.to_str(_, 24)
'1234.567891'
>>> mpmath.libmp.from_str('1_234.567_8_9_1', 80)
(0, mpz(91095031707585398740483), -66, 77)
>>> mpmath.libmp.to_str(_, 24)
'1234.567891'
>>> mpmath.libmp.from_str('1.0_0', 80)
(0, mpz(1), 0, 1)
>>> mpmath.libmp.from_str('.000', 80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/libmp/libmpf.py", line 1331, in from_str
    man, exp = str_to_man_exp(x, base=10)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/libmp/libmpf.py", line 1308, in str_to_man_exp
    x = MPZ(int(x, base))
            ^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```
So, almost everything was fixed, except for last two issues.  We should also add regression tests.
