### ISSUE TITLE
eig() sometimes fails to converge for 8x8 Hadamard matrix

### ISSUE THREAD

**Issue by fredrik-johansson** [mpmath/mpmath#418]
>>> A = matrix([[1, 1, 1, 1, 1, 1, 1, 1], [1, -1, 1, -1, 1, -1, 1, -1], [1, 1, -1, -1, 1, 1, -1, -1], [1, -1, -1, 1, 1, -1, -1, 1], [1, 1, 1, 1, -1, -1, -1, -1], [1, -1, 1, -1, -1, 1, -1, 1], [1, 1, -1, -1, -1, -1, 1, 1], [1, -1, -1, 1, -1, 1, 1, -1]])
    >>> nprint(eig(A),2)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "mpmath/matrices/eigen.py", line 755, in eig
        hessenberg_qr(ctx, A, Q)
      File "mpmath/matrices/eigen.py", line 481, in hessenberg_qr
        raise RuntimeError("qr: failed to converge after %d steps" % its)
    RuntimeError: qr: failed to converge after 61 steps
    >>> mp.prec = 52
    >>> nprint(eig(A),2)
    ([2.8, 2.8, 2.8, 2.8, -2.8, -2.8, -2.8, -2.8], [ -0.11   0.18     0.77  -0.039     -0.3   0.33  -0.35    0.32]
    [   0.3  -0.11     0.36    0.34     -0.3  -0.13  0.094   -0.85]
    [ -0.22  -0.12     0.38    0.46    -0.01   -0.3   0.88  0.0084]
    [ -0.22   0.81    0.082   -0.14  -0.0047   0.16   0.35   -0.45]
    [-0.068   0.36     0.35    0.48     0.74  -0.37  -0.34    0.37]
    [ -0.59  -0.34     0.15   -0.17     0.31   0.13  -0.15    -0.3]
    [  0.67  -0.32    0.087   -0.48     0.42  0.063   0.18   0.058]
    [-0.069  0.052  0.00068   -0.55   0.0048  -0.82   0.33  -0.055])

It appears that it's just down to rounding noise whether it works, suggesting that the algorithm could be made more robust.

**Comment by fredrik-johansson** [comment]
Possible solution: let the user set eps (a larger value should work in this case) and maxits.
