### ISSUE TITLE
Gegenbauer function within mp context throwing ValueError

### ISSUE THREAD

**Issue by jacksonvanover** [mpmath/mpmath#495]
mpmath version: 1.1.0

For the same input, the gegenbauer function in the mp context throws a ValueError while the fp context version returns 0.0 which agrees with SciPy's output.

Example:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> from scipy import special
>>> fp.gegenbauer(1, 2.5, 0)
0.0
>>> special.eval_gegenbauer(1, 2.5, 0)
0.0
>>> mp.gegenbauer(1, 2.5, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mpmath/ctx_mp_python.py", line 1035, in f_wrapped
    retval = f(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/orthogonal.py", line 326, in gegenbauer
    return ctx.hypercomb(h, [n], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/hypergeometric.py", line 127, in hypercomb
    [ctx.rgamma(b) for b in beta_s] + \
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/hypergeometric.py", line 226, in hyper
    if   q == 1: return ctx._hyp2f1(a_s, b_s, z, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/hypergeometric.py", line 443, in _hyp2f1
    return ctx.hypsum(2, 1, (atype, btype, ctype), [a, b, c], z, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/ctx_mp.py", line 708, in hypsum
    raise ValueError(ctx._hypsum_msg % (prec, prec+extraprec))
ValueError: hypsum() failed to converge to the requested 73 bits of accuracy
using a working precision of 3588 bits. Try with a higher maxprec,
maxterms, or set zeroprec.
```

**Comment by skirpichev** [comment]
I don't think it's a real bug.  The exception message shows some hints you could use to compute the value, e.g.:
```pycon
>>> mp.gegenbauer(1, 2.5, 0, zeroprec=1000)
mpf('0.0')
```

@fredrik-johansson ?
