### ISSUE TITLE
Unexpected result from hyp1f1 function in mp context

### ISSUE THREAD

**Issue by jacksonvanover** [mpmath/mpmath#496]
mpmath version: 1.1.0

When the first two arguments are 0, the hyp1f1 function in the mp context returns 1.0 while the fp context version throws a ZeroDivisionError. Based on the series definition of the function, it seems as though the latter is the proper behavior because it implies there is an indeterminate 0/0 calculation.

Example:
```
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from mpmath import *
>>> mp.hyp1f1(0, 0, 0.1)
mpf('1.0')
>>> fp.hyp1f1(0, 0, 0.1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/hypergeometric.py", line 243, in hyp1f1
    return ctx.hyper([a],[b],z,**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/hypergeometric.py", line 222, in hyper
    if   q == 1: return ctx._hyp1f1(a_s, b_s, z, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/functions/hypergeometric.py", line 342, in _hyp1f1
    v = ctx.hypsum(1, 1, (atype, btype), [a, b], z, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/mpmath/ctx_fp.py", line 208, in hypsum
    for i in den: t /= (coeffs[i]+k)
ZeroDivisionError: float division by zero
```

**Comment by skirpichev** [comment]
> Based on the series definition of the function, it seems as though the latter is the proper behavior because it implies there is an indeterminate 0/0 calculation.

No.  Docs says:
> If a nonpositive integer `-n` appears in both ``a_s`` and ``b_s``, this parameter cannot be unambiguously removed since it creates a term 0 / 0.  In this case the hypergeometric series is understood to terminate before the division by zero occurs. This convention is consistent with Mathematica.

So, we should just break if division by zero occurs *and* numerator is already zero.  This is that mp.hypsum does.  And Mathematica:
```
Wolfram Language 14.3.0 Engine for Linux x86 (64-bit)
Copyright 1988-2025 Wolfram Research, Inc.

In[1]:= HypergeometricPFQ[{0}, {0}, z]                                                                                                         

Out[1]= 1
```
