### ISSUE TITLE
Test failed using mpmath.runtests()

### ISSUE THREAD

**Issue by elii94** [mpmath/mpmath#579]
I run the following code in Spyder IDE (Python 3.8):

```
import mpmath
mpmath.runtests()
```
I think that most of the tests passed, but I get 'Test failed'. Attached part of the output:

```
test_power
    fractional_pow            ok        0.0007660 s
    pow_epsilon_rounding      ok        0.0082779 s
    pow_integer_direction     ok        0.0186208 s
test_quad
    basic_integrals           ok        1.0237857 s
    complex_integration       ok        0.0016827 s
    double_1                  ok        0.3531567 s
    double_2                  ok        0.4667540 s
    double_3                  ok        0.7784714 s
    double_4                  ok        0.3646028 s
    double_5                  ok        0.2508498 s
    double_6                  ok        1.3465593 s
    double_7                  ok        5.2399600 s
    double_trivial            ok        0.0525647 s
    expmath_fail              
TEST FAILED!

ok        0.0338242 s
    expmath_integrals         Traceback (most recent call last):
  File "C:\Users\elii\Anaconda3\envs\mpmath_gmpy2_env\lib\site-packages\mpmath\tests\runtests.py", line 118, in testit
    module.__dict__[f]()
  File "C:\Users\elii\Anaconda3\envs\mpmath_gmpy2_env\lib\site-packages\mpmath\tests\test_quad.py", line 88, in test_expmath_fail
    assert ae(quadts(lambda x: sqrt(tan(x)), [0, pi/2]),          pi*sqrt(2)/2)
AssertionError
ok        0.9440781 s
    quad_infinite_mirror      ok        0.0131497 s
    quad_symmetry             ok        0.0015464 s
    quadgl_linear             ok        0.0001529 s
    quadosc                   ok        0.2939415 s
test_rootfinding
    anewton                   ok        0.0027608 s
    bisection                 ok        0.0002725 s
    findroot                  ok        0.0432960 s
    mnewton                   ok        0.0014512 s
    muller                    ok        0.0068285 s
    multidimensional          ok        0.0328756 s
    multiplicity              ok        0.0028072 s
    trivial                   ok        0.0013217 s
test_special
    convert_special           ok        0.0013602 s
    div_bug                   ok        0.0000605 s
    functions_special         ok        0.0002357 s
    special                   ok        0.0005228 s
    special_powers            ok        0.0000924 s
test_str
    nstr                      ok        0.0010739 s
test_summation
    fprod                     ok        0.0000998 s
    fsum                      ok        0.0009567 s
    nprod                     ok        0.0187436 s
    nsum                      ok        0.0945751 s
    sumem                     ok        0.0498782 s
test_trig
    trig_misc_hard            ok        0.0014328 s
    trig_near_n_pi            ok        0.0036418 s
    trig_near_zero            ok        0.0007649 s
test_visualization
    axes                      ok        2.1769707 s

finished tests in 149.44 seconds
```
I tried searching the internet for what the problem might be, but unfortunately I did not find one. Does anyone know what the failure of the test is due to and what can be done to solve this problem?

Note: I worked on an Anaconda environment.

Thank you!

**Comment by mpiraino** [comment]
It looks like this is a test which is expected to fail. It is marked with pytest.mark.xfail. Essentially it is failing because the method quadts is not estimating the integral of certain functions to the precision specified.

**Comment by skirpichev** [comment]
You should use pytest to run tests, see [docs](https://mpmath.org/doc/1.3.0/setup.html#running-tests).
