### ISSUE TITLE
findroot positional argument error

### ISSUE THREAD

**Issue by experiencedft** [mpmath/mpmath#607]
I'm trying to use the `findroot` function with the `illinois` solver. According to [the documentation](https://mpmath.org/doc/current/calculus/optimization.html?highlight=illinois#mpmath.calculus.optimization.Illinois), in the case of this specific solver, the `x0` argument should be the interval used for the search. 

I have a function of one unique scalar variable that I'm trying to find a root for. But when I try to use this method, an error occurs: 

```
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\mpmath\calculus\optimization.py", line 937, in findroot
    fx = f(*x0)
TypeError: func() takes 1 positional argument but 2 were given
```

Here is a minimal working example to reproduce the issue: 

```python
from scipy.stats import norm
import numpy as np 
from mpmath import findroot

R = 0.5
K = 1000
sigma = 0.5
tau = 1
gamma = 0.995
m = 800

EPSILON = 1e-6

def quantilePrime(x):
  return norm.pdf(norm.ppf(x))**-1

def getQuantity(amount_in):
  return gamma*K*norm.pdf(norm.ppf(1 - R - gamma*amount_in) - sigma*np.sqrt(tau))*quantilePrime(1 - R - gamma*amount_in)

def func(amount_in): 
  return getQuantity(amount_in) - m

optimum = findroot(func, (EPSILON, 1 - R + EPSILON), solver='illinois')
```

Is there something I'm missing here?

**Comment by skirpichev** [comment]
@experiencedft, did you provide a full traceback?

I see something like this (numpy 1.21.2 and scipy 1.7.1):
```
$ python a.py 
Traceback (most recent call last):
  File "/home/sk/src/mpmath/mpmath/calculus/optimization.py", line 937, in findroot
    fx = f(*x0)
TypeError: func() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sk/src/mpmath/a.py", line 23, in <module>
    optimum = findroot(func, (EPSILON, 1 - R + EPSILON), solver='illinois')
  File "/home/sk/src/mpmath/mpmath/calculus/optimization.py", line 940, in findroot
    fx = f(x0[0])
  File "/home/sk/src/mpmath/a.py", line 21, in func
    return getQuantity(amount_in) - m
  File "/home/sk/src/mpmath/a.py", line 18, in getQuantity
    return gamma*K*norm.pdf(norm.ppf(1 - R - gamma*amount_in) - sigma*np.sqrt(tau))*quantilePrime(1 - R - gamma*amount_in)
  File "/home/sk/venv/dev/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py", line 2136, in ppf
    place(output, cond, self._ppf(*goodargs) * scale + loc)
  File "/home/sk/venv/dev/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py", line 327, in _ppf
    return _norm_ppf(q)
  File "/home/sk/venv/dev/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py", line 266, in _norm_ppf
    return sc.ndtri(q)
TypeError: ufunc 'ndtri' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

I guess, there might be some problem in the way you mix numpy, scipy & mpmath functions to implement your `func`.  Something simpler works fine with this solver:
```
>>> import mpmath
>>> mpmath.findroot(mpmath.sin, (3, 4), solver ='illinois')
mpf('3.1415926535897932')
```

**Comment by skirpichev** [comment]
@experiencedft, I was able to run your example with few added type casts:
```diff
$ diff a.py b.py 
--- a.py        2023-03-29 06:52:33.806878771 +0300
+++ b.py        2023-03-29 06:53:38.920911124 +0300
@@ -12,12 +12,13 @@
 EPSILON = 1e-6
 
 def quantilePrime(x):
-  return norm.pdf(norm.ppf(x))**-1
+  return norm.pdf(norm.ppf(float(x)))**-1
 
 def getQuantity(amount_in):
-  return gamma*K*norm.pdf(norm.ppf(1 - R - gamma*amount_in) - sigma*np.sqrt(tau))*quantilePrime(1 - R - gamma*amount_in)
+  return gamma*K*norm.pdf(norm.ppf(float(1 - R - gamma*amount_in)) - sigma*np.sqrt(tau))*quantilePrime(1 - R - gamma*amount_in)
 
 def func(amount_in):
   return getQuantity(amount_in) - m
 
 optimum = findroot(func, (EPSILON, 1 - R + EPSILON), solver='illinois')
+print(optimum)
```
The output:
```
$ python b.py 
0.0742516127259866
```

So, I don't think there is something wrong with the mpmath documentation.  The full traceback shows that the problem is with your function, not with the Illinois solver interface (it accepts intervals for x0, yes).
Please reopen the issue, if you disagree or have any ideas on how to improve error reporting in such a situation.
