### ISSUE TITLE
Fix sphinx warnings with nitpicky=True

### ISSUE THREAD

**Issue by kloczek** [mpmath/mpmath#627]
First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/conf.py", line 12, in <module>
    import mpmath
ModuleNotFoundError: No module named 'mpmath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 345, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/conf.py", line 12, in <module>
    import mpmath
ModuleNotFoundError: No module named 'mpmath'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/conf.py", line 12, in <module>
    import mpmath
ModuleNotFoundError: No module named 'mpmath'
```
This can be fixed by patch like below:
```patch
--- a/docs/conf.py~     2022-05-19 10:39:35.000000000 +0000
+++ b/docs/conf.py      2022-05-19 10:41:04.481013587 +0000
@@ -1,3 +1,7 @@
+import sys
+import os
+sys.path.insert(0, os.path.abspath('..'))
+
 """
 Mpmath documentation build configuration file.
```
This patch fixes what is in the comment and that can of fix is suggested in sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file

Than .. on building my packages I'm using `sphinx-build` command with `-n` switch which shows warmings about missing references. These are not critical issues.

Here is the output with warnings:
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v4.5.0
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 33 added, 0 changed, 0 removed
reading sources... [100%] technical
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... mpmath.1 { setup basics contexts general plotting functions/index functions/constants functions/powers functions/trigonometric functions/hyperbolic functions/gamma functions/expintegrals functions/bessel functions/orthogonal functions/hypergeometric functions/elliptic functions/zeta functions/numtheory functions/qfunctions calculus/index calculus/polynomials calculus/optimization calculus/sums_limits calculus/differentiation calculus/integration calculus/odes calculus/approximation calculus/inverselaplace matrices identification technical references } /home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/setup.rst:147: WARNING: py:func reference target not found: call
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/contexts.rst:84: WARNING: py:func reference target not found: repr
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/general.rst:10: WARNING: py:func reference target not found: convert
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp.py:docstring of mpmath.ctx_mp.MPContext.nstr:13: WARNING: py:func reference target not found: mpmath.libmp.to_str
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext.fsum:1: WARNING: py:func reference target not found: sum
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/functions/functions.py:docstring of mpmath.functions.functions.fabs:1: WARNING: py:func reference target not found: abs
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_base.py:docstring of mpmath.ctx_base.StandardBaseContext.arange:1: WARNING: py:func reference target not found: mpmath.range
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_base.py:docstring of mpmath.ctx_base.StandardBaseContext.arange:1: WARNING: py:func reference target not found: mpmath.range
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_base.py:docstring of mpmath.ctx_base.StandardBaseContext.arange:15: WARNING: py:func reference target not found: mpmath.range
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/constants.rst:29: WARNING: py:data reference target not found: j
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/constants.rst:29: WARNING: py:data reference target not found: inf
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/constants.rst:29: WARNING: py:data reference target not found: nan
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/constants.rst:29: WARNING: py:class reference target not found: mpc
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/constants.rst:29: WARNING: py:class reference target not found: mpf
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:34: WARNING: py:func reference target not found: mpmath.iv.sqrt
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/functions/functions.py:docstring of mpmath.functions.functions.root:30: WARNING: py:func reference target not found: mpmath.nthroot
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/functions/functions.py:docstring of mpmath.functions.functions.root:37: WARNING: py:func reference target not found: mpmath.nthroot
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:37: WARNING: py:func reference target not found: mpmath.iv.exp
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:16: WARNING: py:func reference target not found: mpmath.iv.cos
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:16: WARNING: py:func reference target not found: mpmath.iv.sin
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:19: WARNING: py:func reference target not found: mpmath.iv.tan
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_specfun.<locals>.f_wrapped:19: WARNING: py:func reference target not found: mpmath.iv.sec
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_specfun.<locals>.f_wrapped:18: WARNING: py:func reference target not found: mpmath.iv.csc
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_specfun.<locals>.f_wrapped:19: WARNING: py:func reference target not found: mpmath.iv.cot
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/gamma.rst:24: WARNING: py:func reference target not found: fac
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:34: WARNING: py:func reference target not found: mpmath.fac
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_specfun.<locals>.f_wrapped:1: WARNING: py:func reference target not found: mpmath.expint(n,z)
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/hypergeometric.rst:23: WARNING: py:func reference target not found: hypercomb
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/hypergeometric.rst:23: WARNING: py:func reference target not found: hyper
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/hypergeometric.rst:71: WARNING: py:func reference target not found: hyper
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/hypergeometric.rst:75: WARNING: py:func reference target not found: hypercomb
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/functions/elliptic.py:docstring of mpmath.functions.elliptic.ellipfun:15: WARNING: py:func reference target not found: mpmath.nome
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/functions/numtheory.rst:11: WARNING: py:func reference target not found: fib
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/ctx_mp_python.py:docstring of mpmath.ctx_mp_python.PythonMPContext._wrap_libmp_function.<locals>.f:15: WARNING: py:func reference target not found: mpmath.fib
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureMethods.quad:55: WARNING: py:func reference target not found: mpmath.quadts
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureMethods.quad:55: WARNING: py:func reference target not found: mpmath.quadgl
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureMethods.quad:83: WARNING: py:class reference target not found: TanhSinh
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureMethods.quad:83: WARNING: py:class reference target not found: GaussLegendre
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule:10: WARNING: py:func reference target not found: mpmath.__new__
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.calc_nodes:1: WARNING: py:func reference target not found: mpmath.get_nodes
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.get_nodes:1: WARNING: py:func reference target not found: mpmath.calc_nodes
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.get_nodes:6: WARNING: py:func reference target not found: mpmath.calc_nodes
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.guess_degree:11: WARNING: py:func reference target not found: mpmath.guess_degree
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.sum_next:4: WARNING: py:func reference target not found: mpmath.summation
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.sum_next:4: WARNING: py:func reference target not found: mpmath.sum_next
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.summation:1: WARNING: py:func reference target not found: mpmath.estimate_error
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.summation:6: WARNING: py:func reference target not found: mpmath.summation
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/quadrature.py:docstring of mpmath.calculus.quadrature.QuadratureRule.summation:6: WARNING: py:func reference target not found: mpmath.sum_next
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/inverselaplace.py:docstring of mpmath.calculus.inverselaplace.LaplaceTransformInversionMethods.invertlaplace:97: WARNING: py:func reference target not found: mpmath.invlaptalbot
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/inverselaplace.py:docstring of mpmath.calculus.inverselaplace.LaplaceTransformInversionMethods.invertlaplace:97: WARNING: py:func reference target not found: mpmath.invlapstehfest
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/calculus/inverselaplace.py:docstring of mpmath.calculus.inverselaplace.LaplaceTransformInversionMethods.invertlaplace:97: WARNING: py:func reference target not found: mpmath.invlapdehoog
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/identification.py:docstring of mpmath.identification.identify:154: WARNING: py:func reference target not found: mpmath.eval
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/identification.py:docstring of mpmath.identification.identify:163: WARNING: py:func reference target not found: mpmath.sympify
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/mpmath/identification.py:docstring of mpmath.identification.identify:187: WARNING: py:func reference target not found: mpmath.nsimplify
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/technical.rst:98: WARNING: py:func reference target not found: str
/home/tkloczko/rpmbuild/BUILD/mpmath-1.2.1/docs/technical.rst:98: WARNING: py:func reference target not found: repr
done
build succeeded, 56 warnings.
```
You can peak on fixes that kind of issues in other projects
https://github.com/latchset/jwcrypto/pull/289
https://github.com/click-contrib/sphinx-click/commit/abc31069

**Comment by skirpichev** [comment]
> First of all currently it is not possible to use straight sphinx-build command to build documentation out of source tree

That's not true:
```
$ python3.11 -m venv tmp
$ . tmp/bin/activate
$ pip install -U -e .[docs,gmpy,develop]
$ sphinx-build --color -W --keep-going -b html docs build/sphinx/html
Running Sphinx v6.1.3
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 34 source files that are out of date
updating environment: [new config] 34 added, 0 changed, 0 removed
reading sources... [100%] technical                                                                                                                           
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] technical                                                                                                                            
generating indices... genindex py-modindex done
writing additional pages... search done
copying images... [100%] splot.png                                                                                                                            
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.
```
> I'm using sphinx-build command with -n switch which shows warmings about missing references

Yes, this should be fixed.

**Comment by kloczek** [comment]
> > First of all currently it is not possible to use straight sphinx-build command to build documentation out of source tree
> 
> That's not true:

Did you try to executr that command without have installed `mpmath` module? 🤔 
I'm asking because it was my case which ahappens during typical rpm package build when it is not possible to install module which is just packaged.

**Comment by skirpichev** [comment]
In this case you could add `PYTHONPATH=.` before above sphinx-build command.  Using above patch probably will break users expectations in case of usual "pip install ." (i.e. non-editable) setups.

**Comment by kloczek** [comment]
> In this case you could add `PYTHONPATH=.` before above sphinx-build command. Using above patch probably will break users expectations in case of usual "pip install ." (i.e. non-editable) setups.

Nope .. I'm using that +1.5 years and none of the effects.

And yes that is true about possibility of passing path in `$PYTHONPATH` however if it needs to be packaged some bigger number of python modules (I have now +1.1k such packages) which actual base directory may be like in your case just `.` or for example `src/` or other) it would require to customise each documentation build procedure to pass proper path in `$PYTHONPATH`.
At the moment majority of all modules which have already have proper alteration of the `sys.path` in conf.py.
All because `sys.path` altering is mentioned in sphinx example copy.py https://www.sphinx-doc.org/en/master/usage/configuration.html#example-of-configuration-file.

So using all my sepc files .. at the moment I have:
```console
[tkloczko@pers-jacek SPECS]$ grep %pyproject_wheel *spec | wc -l
1133
```
spec files which are using pep517 based build procedure to generate .whl archive which is used to form rpm package.
Amongst those packages
```console
[tkloczko@pers-jacek SPECS]$ grep %pyproject_wheel *spec -l | xargs grep -l %sphinx_build_man | wc -l
540
```
packages have sphinx based documentation which I'm using to render module man page.
And amongs those packages
```console
[tkloczko@pers-jacek SPECS]$ grep %pyproject_wheel *spec -l | xargs grep -l %sphinx_build_man -l | xargs grep %{name}-add_module_path_in_conf.py.patch | wc -l
192
```
ATM requires conf.py patch to add proper path to base directory to be able build module documentation without have module installed.
That number will be going down because recently I've started pushing those changes into VCS repos and in most of the cases such patch is accepted.

From that point of view all above forms kind of platform allowing generate modules documentation no matter where exactly module base directory is in VCS tree (in `<module/>` or `src/<module/> or other location).

And at the end it is even yet more important another reason to use above approach.
Simple if in conf.py will be added `sys.path` alteration no matter do you have installed module or not `sphinx-build` will ALWAYS generate agains what is in source tree and not what is installed 😄 

So above is kind of complete argumentation why it is better™️ to integrate such small patch directly into original VCS tree and not thing to much about other alternative procedures😋

**Comment by skirpichev** [comment]
> Nope .. I'm using that +1.5 years and none of the effects.

An example:
```
$ python3.11 -m venv tmp
$ . tmp/bin/activate
$ pip install -U .[docs,gmpy,develop]  # a non-editable install
$ git diff  # break things
diff --git a/mpmath/__init__.py b/mpmath/__init__.py
index 46a7c6f..efe97f3 100644
--- a/mpmath/__init__.py
+++ b/mpmath/__init__.py
@@ -1,3 +1,4 @@
+raise ImportError
 __version__ = '1.3.0'
 
 from .usertools import monitor, timing

$ sphinx-build --color -W --keep-going -b html docs build/sphinx/html  # PASS!
$ git diff docs/  # now with your patch
diff --git a/docs/conf.py b/docs/conf.py
index 62a654c..a0e9158 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -9,6 +9,10 @@
 removed automatically).
 """
 
+import sys
+import os
+sys.path.insert(0, os.path.abspath('..'))
+
 import mpmath
 
 
$ sphinx-build --color -W --keep-going -b html docs build/sphinx/html  # FAIL!
```

My guess, that the second case people could expect for editable installs, but not in the case they just hack the prose docs.  That's why I slightly -0 about this "feature":)
