### ISSUE TITLE
asinh returns incorrect results at complex infinities

### ISSUE THREAD

**Issue by pearu** [mpmath/mpmath#749]
As in the title.

Reproducer (using mpmath 1.3.0):
```python
>>> mpmath.asinh(mpmath.mpc(mpmath.inf, 0))
mpc(real='0.0', imag='0.0')
```
Expected result is `mpc(real='+inf', imag='0.0')` as in
```python
>>> mpmath.asinh(mpmath.inf)
mpf('+inf')
```

Another reproducer:
```python
>>> mpmath.asinh(mpmath.mpc(mpmath.inf, 1))
mpc(real='0.0', imag='0.0')
```
Expected result is `mpc(real='+inf', imag='0.0')` per https://en.cppreference.com/w/cpp/numeric/complex/asinh

**Comment by skirpichev** [comment]
In fact, there are more issues.

I can reproduce above without gmpy in the current master:
```
$ MPMATH_NOGMPY=Y python -q
>>> from mpmath import *
>>> mp.asinh(mp.mpc(mp.inf, 0))
mpc(real='0.0', imag='0.0')
```
On another hand:
```
>>> fp.asinh(fp.mpc(fp.inf, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'FPContext' object has no attribute 'asinh'. Did you mean: 'asin'?
```

And with gmpy2:
```
>>> mp.asinh(mp.mpc(mp.inf, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sk/src/mpmath/mpmath/ctx_mp_python.py", line 1118, in f
    return ctx.make_mpc(mpc_f(x._mpc_, prec, rounding))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/libmp/libmpc.py", line 739, in mpc_asinh
    a, b =  mpc_asin((b, mpf_neg(a)), prec, rnd)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/libmp/libmpc.py", line 734, in mpc_asin
    return acos_asin(z, prec, rnd, 1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sk/src/mpmath/mpmath/libmp/libmpc.py", line 727, in acos_asin
    im = normalize(im[0], im[1], im[2], im[3], prec, rnd)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: arguments long, MPZ_Object*, PyObject*, long, long, char needed
```

**Comment by skirpichev** [comment]
#750
