### ISSUE TITLE
Unable to compute mpmath.legenp(Even number, Odd number, 0)

### ISSUE THREAD

**Issue by hsiatein** [mpmath/mpmath#780]
My code:
![image](https://github.com/mpmath/mpmath/assets/116558762/1e144774-aeb4-4f37-b3e2-68b67a05fbf6)

And output:
C:\Users\30236\mpmathtest\Scripts\python.exe D:\python\mpmathtest\main.py 
Traceback (most recent call last):
  File "D:\python\mpmathtest\main.py", line 3, in <module>
    print(mpmath.legenp(10,1,0))
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30236\mpmathtest\Lib\site-packages\mpmath\functions\orthogonal.py", line 379, in legenp
    return ctx.hypercomb(h, [n,m], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30236\mpmathtest\Lib\site-packages\mpmath\functions\hypergeometric.py", line 125, in hypercomb
    v = ctx.fprod([ctx.hyper(a_s, b_s, z, **kwargs)] + \
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30236\mpmathtest\Lib\site-packages\mpmath\functions\hypergeometric.py", line 226, in hyper
    if   q == 1: return ctx._hyp2f1(a_s, b_s, z, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30236\mpmathtest\Lib\site-packages\mpmath\functions\hypergeometric.py", line 443, in _hyp2f1
    return ctx.hypsum(2, 1, (atype, btype, ctype), [a, b, c], z, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\30236\mpmathtest\Lib\site-packages\mpmath\ctx_mp.py", line 708, in hypsum
    raise ValueError(ctx._hypsum_msg % (prec, prec+extraprec))
ValueError: hypsum() failed to converge to the requested 1964 bits of accuracy
using a working precision of 5479 bits. Try with a higher maxprec,
maxterms, or set zeroprec.

Then I tried several other parameter combinations and found that the program was unable to compute mpmath.legenp(Even number, Odd number, 0).

for example mpmath.legenp(2, 1, 0), mpmath.legenp(4, 1, 0), mpmath.legenp(4, 3, 0)...

**Comment by skirpichev** [comment]
JFR,
```pycon
>>> legenp(2, 1, 0, zeroprec=1000)
mpf('0.0')
>>> legenp(4, 1, 0, zeroprec=1000)
mpf('0.0')
>>> legenp(4, 3, 0, zeroprec=1000)
mpf('0.0')
```

Closed, see https://github.com/mpmath/mpmath/issues/248.
